
version: '3'

services:
  backend:
    image: shroukibrahim/server
    ports:
      - "5000:5000"
  frontend:
    image: shroukibrahim/web
    ports:
      - "3000:3000"
    depends_on:
      - backend
